// <auto-generated />
using System;
using AgroMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroMonitor.Migrations
{
    [DbContext(typeof(AgroMonitorDbContext))]
    [Migration("20251208032737_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AgroMonitor.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCultivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFinca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NivelPrioridad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdCultivo");

                    b.HasIndex("IdFinca");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("AgroMonitor.Models.Cultivo", b =>
                {
                    b.Property<int>("IdCultivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCosechaEstimada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSiembra")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFinca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoCultivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCultivo");

                    b.HasIndex("IdFinca");

                    b.ToTable("Cultivos");
                });

            modelBuilder.Entity("AgroMonitor.Models.Finca", b =>
                {
                    b.Property<int>("IdFinca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AreaTareas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NombreFinca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicacionText")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdFinca");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Fincas");
                });

            modelBuilder.Entity("AgroMonitor.Models.LecturaSensor", b =>
                {
                    b.Property<long>("IdLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSensor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProcesadoML")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("IdLectura");

                    b.HasIndex("IdSensor");

                    b.ToTable("LecturasSensor");
                });

            modelBuilder.Entity("AgroMonitor.Models.RecomendacionML", b =>
                {
                    b.Property<int>("IdRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confianza")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCultivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoRecomendacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRec");

                    b.HasIndex("IdCultivo");

                    b.ToTable("RecomendacionesML");
                });

            modelBuilder.Entity("AgroMonitor.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGenerado")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFinca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdFinca");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("AgroMonitor.Models.Sensor", b =>
                {
                    b.Property<int>("IdSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFinca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentificadorExterno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstaladoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicacionEnFinca")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoCheck")
                        .HasColumnType("TEXT");

                    b.HasKey("IdSensor");

                    b.HasIndex("IdFinca");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("AgroMonitor.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AgroMonitor.Models.Alerta", b =>
                {
                    b.HasOne("AgroMonitor.Models.Cultivo", "Cultivo")
                        .WithMany("Alertas")
                        .HasForeignKey("IdCultivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroMonitor.Models.Finca", "Finca")
                        .WithMany("Alertas")
                        .HasForeignKey("IdFinca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cultivo");

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("AgroMonitor.Models.Cultivo", b =>
                {
                    b.HasOne("AgroMonitor.Models.Finca", "Finca")
                        .WithMany("Cultivos")
                        .HasForeignKey("IdFinca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("AgroMonitor.Models.Finca", b =>
                {
                    b.HasOne("AgroMonitor.Models.Usuario", "Usuario")
                        .WithMany("Fincas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgroMonitor.Models.LecturaSensor", b =>
                {
                    b.HasOne("AgroMonitor.Models.Sensor", "Sensor")
                        .WithMany("Lecturas")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AgroMonitor.Models.RecomendacionML", b =>
                {
                    b.HasOne("AgroMonitor.Models.Cultivo", "Cultivo")
                        .WithMany("Recomendaciones")
                        .HasForeignKey("IdCultivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultivo");
                });

            modelBuilder.Entity("AgroMonitor.Models.Reporte", b =>
                {
                    b.HasOne("AgroMonitor.Models.Finca", "Finca")
                        .WithMany("Reportes")
                        .HasForeignKey("IdFinca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgroMonitor.Models.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Finca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgroMonitor.Models.Sensor", b =>
                {
                    b.HasOne("AgroMonitor.Models.Finca", "Finca")
                        .WithMany("Sensores")
                        .HasForeignKey("IdFinca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");
                });

            modelBuilder.Entity("AgroMonitor.Models.Cultivo", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Recomendaciones");
                });

            modelBuilder.Entity("AgroMonitor.Models.Finca", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Cultivos");

                    b.Navigation("Reportes");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("AgroMonitor.Models.Sensor", b =>
                {
                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("AgroMonitor.Models.Usuario", b =>
                {
                    b.Navigation("Fincas");

                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
